name: Fork Sync

on:
  schedule:
    - cron: '* * * * 6' # every Saturday
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: ZigmundRat
          base: master
          head: master
